package com.mycompany.common;

public enum Primitiva {
  REGISTER_REQ,
  REGISTER_RES,
  LOGIN_REQ,
  LOGIN_RES,
  SEND_CHANNEL_MSG_REQ,
  SEND_CHANNEL_NOTIFICATION,
  SEND_PRIV_NOTIFICATION,
  GET_CHANNELS_REQ,
  GET_CHANNELS_RES,
  JOIN_CHANNEL_REQ,
  JOIN_CHANNEL_RES,
  LEAVE_CHANNEL_REQ,
  LEAVE_CHANNEL_RES,
  NOTIFY_JOIN,
  LOGOUT_REQ,
  LOGOUT_RES,
  HEARTBEAT,
  HEARTBEAT_ACK,
  HISTORY_REQ,
  HISTORY_RES,
  ERROR_RES
}
